services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: harmonico-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_URL=http://backend-api:3001
    networks:
      - harmonico-net

  backend-api:
    build:
      context: .
      dockerfile: apps/server-api/Dockerfile
    container_name: harmonico-api
    restart: always
    ports:
      - "3001:3001"
    networks:
      - harmonico-net

networks:
  harmonico-net:
    driver: bridge
